CREATE TABLE trelloclone_boards (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  creator INTEGER REFERENCES trelloclone_users(id),
  date_created TIMESTAMP DEFAULT now() NOT NULL
);